package com.frostox.calculo.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.frostox.calculo.Entities.User;
import com.frostox.calculo.Entities.Logged;
import com.frostox.calculo.Entities.Standard;
import com.frostox.calculo.Entities.Subject;
import com.frostox.calculo.Entities.Topic;
import com.frostox.calculo.Entities.Mcq;
import com.frostox.calculo.Entities.McqItem;
import com.frostox.calculo.Entities.Note;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig loggedDaoConfig;
    private final DaoConfig standardDaoConfig;
    private final DaoConfig subjectDaoConfig;
    private final DaoConfig topicDaoConfig;
    private final DaoConfig mcqDaoConfig;
    private final DaoConfig mcqItemDaoConfig;
    private final DaoConfig noteDaoConfig;

    private final UserDao userDao;
    private final LoggedDao loggedDao;
    private final StandardDao standardDao;
    private final SubjectDao subjectDao;
    private final TopicDao topicDao;
    private final McqDao mcqDao;
    private final McqItemDao mcqItemDao;
    private final NoteDao noteDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        loggedDaoConfig = daoConfigMap.get(LoggedDao.class).clone();
        loggedDaoConfig.initIdentityScope(type);

        standardDaoConfig = daoConfigMap.get(StandardDao.class).clone();
        standardDaoConfig.initIdentityScope(type);

        subjectDaoConfig = daoConfigMap.get(SubjectDao.class).clone();
        subjectDaoConfig.initIdentityScope(type);

        topicDaoConfig = daoConfigMap.get(TopicDao.class).clone();
        topicDaoConfig.initIdentityScope(type);

        mcqDaoConfig = daoConfigMap.get(McqDao.class).clone();
        mcqDaoConfig.initIdentityScope(type);

        mcqItemDaoConfig = daoConfigMap.get(McqItemDao.class).clone();
        mcqItemDaoConfig.initIdentityScope(type);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        loggedDao = new LoggedDao(loggedDaoConfig, this);
        standardDao = new StandardDao(standardDaoConfig, this);
        subjectDao = new SubjectDao(subjectDaoConfig, this);
        topicDao = new TopicDao(topicDaoConfig, this);
        mcqDao = new McqDao(mcqDaoConfig, this);
        mcqItemDao = new McqItemDao(mcqItemDaoConfig, this);
        noteDao = new NoteDao(noteDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Logged.class, loggedDao);
        registerDao(Standard.class, standardDao);
        registerDao(Subject.class, subjectDao);
        registerDao(Topic.class, topicDao);
        registerDao(Mcq.class, mcqDao);
        registerDao(McqItem.class, mcqItemDao);
        registerDao(Note.class, noteDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        loggedDaoConfig.getIdentityScope().clear();
        standardDaoConfig.getIdentityScope().clear();
        subjectDaoConfig.getIdentityScope().clear();
        topicDaoConfig.getIdentityScope().clear();
        mcqDaoConfig.getIdentityScope().clear();
        mcqItemDaoConfig.getIdentityScope().clear();
        noteDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public LoggedDao getLoggedDao() {
        return loggedDao;
    }

    public StandardDao getStandardDao() {
        return standardDao;
    }

    public SubjectDao getSubjectDao() {
        return subjectDao;
    }

    public TopicDao getTopicDao() {
        return topicDao;
    }

    public McqDao getMcqDao() {
        return mcqDao;
    }

    public McqItemDao getMcqItemDao() {
        return mcqItemDao;
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

}
