package com.frostox.calculo.Entities;

import com.frostox.calculo.dao.DaoSession;
import com.frostox.calculo.dao.StandardDao;
import com.frostox.calculo.dao.SubjectDao;
import com.frostox.calculo.interfaces.EntityGetter;

import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SUBJECT".
 */
public class Subject implements EntityGetter{

    private Long id;
    /** Not-null value. */
    private String name;
    private Long standardId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient SubjectDao myDao;

    private Standard standard;
    private Long standard__resolvedKey;


    public Subject() {
    }

    public Subject(Long id) {
        this.id = id;
    }

    public Subject(Long id, String name, Long standardId) {
        this.id = id;
        this.name = name;
        this.standardId = standardId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getSubjectDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public Long getStandardId() {
        return standardId;
    }

    public void setStandardId(Long standardId) {
        this.standardId = standardId;
    }

    /** To-one relationship, resolved on first access. */
    public Standard getStandard() {
        Long __key = this.standardId;
        if (standard__resolvedKey == null || !standard__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            StandardDao targetDao = daoSession.getStandardDao();
            Standard standardNew = targetDao.load(__key);
            synchronized (this) {
                standard = standardNew;
            	standard__resolvedKey = __key;
            }
        }
        return standard;
    }

    public void setStandard(Standard standard) {
        synchronized (this) {
            this.standard = standard;
            standardId = standard == null ? null : standard.getId();
            standard__resolvedKey = standardId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
